# Generated by Django 6.0.3 on 2026-04-28 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('correction', 'Correction'), ('parallel_text', 'Parallel Text'), ('flagged_data', 'Flagged Data')], max_length=30)),
                ('content', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_moderation', 'Needs Moderation')], default='pending', max_length=30)),
                ('yes_votes', models.PositiveIntegerField(default=0)),
                ('no_votes', models.PositiveIntegerField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('required_votes', models.PositiveIntegerField(default=20)),
                ('validated_by', models.CharField(choices=[('system', 'System'), ('moderator', 'Moderator'), ('none', 'None')], default='none', max_length=30)),
                ('source_type', models.CharField(blank=True, help_text='Model name of the originating dataset record.', max_length=50, null=True)),
                ('source_id', models.PositiveIntegerField(blank=True, help_text='PK of the originating dataset record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source_type', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='ValidationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='validation.validationitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('item', 'user')},
            },
        ),
    ]
