# Generated by Django 6.0.3 on 2026-05-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationitem",
            name="neutral_votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="validationvote",
            name="response",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("neutral", "Neutral")],
                max_length=10,
            ),
        ),
    ]
