# Generated by Django 6.0.3 on 2026-06-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0002_validationitem_neutral_votes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationitem",
            name="required_votes",
            field=models.PositiveIntegerField(default=6),
        ),
    ]
